### ISSUE TITLE
deepstream 3.1.0 crash on this._handleForceWriteAcknowledgement is not a function

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io#825]
Worked fine on deepstream 3.0.1 but crashed immediately on starting backend client. Was there API change between deepstream 3.0.1 and 3.1.0?

```
C:\Projects\DS\server\deepstream\lib\deepstream.io-cache-redis\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: this._handleForceWriteAcknowledgement is not a function
    at _options.cache.set ([eval]:47684:14)
    at tryCatcher (C:\Projects\DS\server\deepstream\lib\deepstream.io-cache-redis\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Projects\DS\server\deepstream\lib\deepstream.io-cache-redis\node_modules\bluebird\js\release\nodeify.js:23:30)
    at Promise._settlePromise (C:\Projects\DS\server\deepstream\lib\deepstream.io-cache-redis\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Projects\DS\server\deepstream\lib\deepstream.io-cache-redis\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Projects\DS\server\deepstream\lib\deepstream.io-cache-redis\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Projects\DS\server\deepstream\lib\deepstream.io-cache-redis\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Projects\DS\server\deepstream\lib\deepstream.io-cache-redis\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Projects\DS\server\deepstream\lib\deepstream.io-cache-redis\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by AlexBHarley** [comment]
Thanks for this, looks like a regression that was introduced between 3.0.1 and 3.1.0.

Fixed in 3.1.1

**Comment by layanto** [comment]
Looks like Windows build of deepstream 3.1.1 still missing.
